# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import face_analysis_layer_pb2 as face__analysis__layer__pb2
# import face_analysis_layer_pb2 as face__analysis__layer__pb2


class FaceAnalysisLayerStub(object):
    """Service definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.FaceRekognitionModelOutputRequestHandler = channel.unary_stream(
                '/information_superhighway.FaceAnalysisLayer/FaceRekognitionModelOutputRequestHandler',
                request_serializer=face__analysis__layer__pb2.FaceRekognitionModelOutputRequest.SerializeToString,
                response_deserializer=face__analysis__layer__pb2.FaceStatusReply.FromString,
                )


class FaceAnalysisLayerServicer(object):
    """Service definition
    """

    def FaceRekognitionModelOutputRequestHandler(self, request, context):
        """AI output request
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FaceAnalysisLayerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'FaceRekognitionModelOutputRequestHandler': grpc.unary_stream_rpc_method_handler(
                    servicer.FaceRekognitionModelOutputRequestHandler,
                    request_deserializer=face__analysis__layer__pb2.FaceRekognitionModelOutputRequest.FromString,
                    response_serializer=face__analysis__layer__pb2.FaceStatusReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'information_superhighway.FaceAnalysisLayer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class FaceAnalysisLayer(object):
    """Service definition
    """

    @staticmethod
    def FaceRekognitionModelOutputRequestHandler(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/information_superhighway.FaceAnalysisLayer/FaceRekognitionModelOutputRequestHandler',
            face__analysis__layer__pb2.FaceRekognitionModelOutputRequest.SerializeToString,
            face__analysis__layer__pb2.FaceStatusReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
