# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import evidence_model_pb2 as evidence__model__pb2


class EvidenceModelServiceStub(object):
    """Service definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.EvidenceAnalysisRequestHandler = channel.unary_stream(
                '/evidence_model.EvidenceModelService/EvidenceAnalysisRequestHandler',
                request_serializer=evidence__model__pb2.EvidenceRequest.SerializeToString,
                response_deserializer=evidence__model__pb2.EvidenceReply.FromString,
                )


class EvidenceModelServiceServicer(object):
    """Service definition
    """

    def EvidenceAnalysisRequestHandler(self, request, context):
        """AI analysis request
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EvidenceModelServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'EvidenceAnalysisRequestHandler': grpc.unary_stream_rpc_method_handler(
                    servicer.EvidenceAnalysisRequestHandler,
                    request_deserializer=evidence__model__pb2.EvidenceRequest.FromString,
                    response_serializer=evidence__model__pb2.EvidenceReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'evidence_model.EvidenceModelService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class EvidenceModelService(object):
    """Service definition
    """

    @staticmethod
    def EvidenceAnalysisRequestHandler(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/evidence_model.EvidenceModelService/EvidenceAnalysisRequestHandler',
            evidence__model__pb2.EvidenceRequest.SerializeToString,
            evidence__model__pb2.EvidenceReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
