# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: evidence_model.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x65vidence_model.proto\x12\x0e\x65vidence_model\"-\n\x0f\x45videnceRequest\x12\x1a\n\x12project_table_name\x18\x01 \x01(\t\" \n\rEvidenceReply\x12\x0f\n\x07message\x18\x01 \x01(\t2|\n\x14\x45videnceModelService\x12\x64\n\x1e\x45videnceAnalysisRequestHandler\x12\x1f.evidence_model.EvidenceRequest\x1a\x1d.evidence_model.EvidenceReply\"\x00\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'evidence_model_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_EVIDENCEREQUEST']._serialized_start=40
  _globals['_EVIDENCEREQUEST']._serialized_end=85
  _globals['_EVIDENCEREPLY']._serialized_start=87
  _globals['_EVIDENCEREPLY']._serialized_end=119
  _globals['_EVIDENCEMODELSERVICE']._serialized_start=121
  _globals['_EVIDENCEMODELSERVICE']._serialized_end=245
# @@protoc_insertion_point(module_scope)
