# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import image_classification_analysis_layer_pb2 as image__classification__analysis__layer__pb2


class ImageClassificationAnalysisLayerStub(object):
    """Service definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ImageClassificationModelOutputRequestHandler = channel.unary_stream(
                '/information_superhighway.ImageClassificationAnalysisLayer/ImageClassificationModelOutputRequestHandler',
                request_serializer=image__classification__analysis__layer__pb2.ImageClassificationModelOutputRequest.SerializeToString,
                response_deserializer=image__classification__analysis__layer__pb2.StatusReply.FromString,
                )


class ImageClassificationAnalysisLayerServicer(object):
    """Service definition
    """

    def ImageClassificationModelOutputRequestHandler(self, request, context):
        """AI output request
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ImageClassificationAnalysisLayerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ImageClassificationModelOutputRequestHandler': grpc.unary_stream_rpc_method_handler(
                    servicer.ImageClassificationModelOutputRequestHandler,
                    request_deserializer=image__classification__analysis__layer__pb2.ImageClassificationModelOutputRequest.FromString,
                    response_serializer=image__classification__analysis__layer__pb2.StatusReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'information_superhighway.ImageClassificationAnalysisLayer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ImageClassificationAnalysisLayer(object):
    """Service definition
    """

    @staticmethod
    def ImageClassificationModelOutputRequestHandler(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/information_superhighway.ImageClassificationAnalysisLayer/ImageClassificationModelOutputRequestHandler',
            image__classification__analysis__layer__pb2.ImageClassificationModelOutputRequest.SerializeToString,
            image__classification__analysis__layer__pb2.StatusReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
