# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: image_classification_analysis_layer.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n)image_classification_analysis_layer.proto\x12\x18information_superhighway\"\x80\x01\n%ImageClassificationModelOutputRequest\x12\x1a\n\x12project_table_name\x18\x01 \x01(\t\x12\x10\n\x08photo_id\x18\x02 \x01(\x05\x12)\n!labels_from_classifications_model\x18\x03 \x03(\x0c\"3\n\x0bStatusReply\x12\x10\n\x08photo_id\x18\x01 \x01(\x03\x12\x12\n\nmodel_name\x18\x02 \x01(\t2\xbd\x01\n ImageClassificationAnalysisLayer\x12\x98\x01\n,ImageClassificationModelOutputRequestHandler\x12?.information_superhighway.ImageClassificationModelOutputRequest\x1a%.information_superhighway.StatusReply0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'image_classification_analysis_layer_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_IMAGECLASSIFICATIONMODELOUTPUTREQUEST']._serialized_start=72
  _globals['_IMAGECLASSIFICATIONMODELOUTPUTREQUEST']._serialized_end=200
  _globals['_STATUSREPLY']._serialized_start=202
  _globals['_STATUSREPLY']._serialized_end=253
  _globals['_IMAGECLASSIFICATIONANALYSISLAYER']._serialized_start=256
  _globals['_IMAGECLASSIFICATIONANALYSISLAYER']._serialized_end=445
# @@protoc_insertion_point(module_scope)
