# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: similarity_model.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16similarity_model.proto\x12\x10similarity_model\"/\n\x11SimilarityRequest\x12\x1a\n\x12project_table_name\x18\x01 \x01(\t\"\"\n\x0fSimilarityReply\x12\x0f\n\x07message\x18\x01 \x01(\t2\x88\x01\n\x16SimilarityModelService\x12n\n SimilarityAnalysisRequestHandler\x12#.similarity_model.SimilarityRequest\x1a!.similarity_model.SimilarityReply\"\x00\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'similarity_model_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SIMILARITYREQUEST']._serialized_start=44
  _globals['_SIMILARITYREQUEST']._serialized_end=91
  _globals['_SIMILARITYREPLY']._serialized_start=93
  _globals['_SIMILARITYREPLY']._serialized_end=127
  _globals['_SIMILARITYMODELSERVICE']._serialized_start=130
  _globals['_SIMILARITYMODELSERVICE']._serialized_end=266
# @@protoc_insertion_point(module_scope)
