# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import similarity_model_pb2 as similarity__model__pb2


class SimilarityModelServiceStub(object):
    """Service definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SimilarityAnalysisRequestHandler = channel.unary_stream(
                '/similarity_model.SimilarityModelService/SimilarityAnalysisRequestHandler',
                request_serializer=similarity__model__pb2.SimilarityRequest.SerializeToString,
                response_deserializer=similarity__model__pb2.SimilarityReply.FromString,
                )


class SimilarityModelServiceServicer(object):
    """Service definition
    """

    def SimilarityAnalysisRequestHandler(self, request, context):
        """AI analysis request
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SimilarityModelServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SimilarityAnalysisRequestHandler': grpc.unary_stream_rpc_method_handler(
                    servicer.SimilarityAnalysisRequestHandler,
                    request_deserializer=similarity__model__pb2.SimilarityRequest.FromString,
                    response_serializer=similarity__model__pb2.SimilarityReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'similarity_model.SimilarityModelService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SimilarityModelService(object):
    """Service definition
    """

    @staticmethod
    def SimilarityAnalysisRequestHandler(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/similarity_model.SimilarityModelService/SimilarityAnalysisRequestHandler',
            similarity__model__pb2.SimilarityRequest.SerializeToString,
            similarity__model__pb2.SimilarityReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
