# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import template_ai_model_pb2 as template__ai__model__pb2


class AiModelTemplateServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AiModelTemplateRequest = channel.unary_stream(
                '/template_ai_model.AiModelTemplateService/AiModelTemplateRequest',
                request_serializer=template__ai__model__pb2.AiTemplateRequest.SerializeToString,
                response_deserializer=template__ai__model__pb2.AiTemplateReply.FromString,
                )


class AiModelTemplateServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AiModelTemplateRequest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AiModelTemplateServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AiModelTemplateRequest': grpc.unary_stream_rpc_method_handler(
                    servicer.AiModelTemplateRequest,
                    request_deserializer=template__ai__model__pb2.AiTemplateRequest.FromString,
                    response_serializer=template__ai__model__pb2.AiTemplateReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'template_ai_model.AiModelTemplateService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AiModelTemplateService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AiModelTemplateRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/template_ai_model.AiModelTemplateService/AiModelTemplateRequest',
            template__ai__model__pb2.AiTemplateRequest.SerializeToString,
            template__ai__model__pb2.AiTemplateReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
