# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: template_ai_model.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17template_ai_model.proto\x12\x11template_ai_model\"!\n\x11\x41iTemplateRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\"\n\x0f\x41iTemplateReply\x12\x0f\n\x07message\x18\x01 \x01(\t2~\n\x16\x41iModelTemplateService\x12\x64\n\x16\x41iModelTemplateRequest\x12$.template_ai_model.AiTemplateRequest\x1a\".template_ai_model.AiTemplateReply0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'template_ai_model_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_AITEMPLATEREQUEST']._serialized_start=46
  _globals['_AITEMPLATEREQUEST']._serialized_end=79
  _globals['_AITEMPLATEREPLY']._serialized_start=81
  _globals['_AITEMPLATEREPLY']._serialized_end=115
  _globals['_AIMODELTEMPLATESERVICE']._serialized_start=117
  _globals['_AIMODELTEMPLATESERVICE']._serialized_end=243
# @@protoc_insertion_point(module_scope)
