# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: topic_model.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11topic_model.proto\x12\x0btopic_model\"*\n\x0cTopicRequest\x12\x1a\n\x12project_table_name\x18\x01 \x01(\t\"\x1d\n\nTopicReply\x12\x0f\n\x07message\x18\x01 \x01(\t2j\n\x11TopicModelService\x12U\n\x1bTopicAnalysisRequestHandler\x12\x19.topic_model.TopicRequest\x1a\x17.topic_model.TopicReply\"\x00\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'topic_model_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_TOPICREQUEST']._serialized_start=34
  _globals['_TOPICREQUEST']._serialized_end=76
  _globals['_TOPICREPLY']._serialized_start=78
  _globals['_TOPICREPLY']._serialized_end=107
  _globals['_TOPICMODELSERVICE']._serialized_start=109
  _globals['_TOPICMODELSERVICE']._serialized_end=215
# @@protoc_insertion_point(module_scope)
