# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import topic_model_pb2 as topic__model__pb2


class TopicModelServiceStub(object):
    """Service definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.TopicAnalysisRequestHandler = channel.unary_stream(
                '/topic_model.TopicModelService/TopicAnalysisRequestHandler',
                request_serializer=topic__model__pb2.TopicRequest.SerializeToString,
                response_deserializer=topic__model__pb2.TopicReply.FromString,
                )


class TopicModelServiceServicer(object):
    """Service definition
    """

    def TopicAnalysisRequestHandler(self, request, context):
        """AI analysis request
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TopicModelServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'TopicAnalysisRequestHandler': grpc.unary_stream_rpc_method_handler(
                    servicer.TopicAnalysisRequestHandler,
                    request_deserializer=topic__model__pb2.TopicRequest.FromString,
                    response_serializer=topic__model__pb2.TopicReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'topic_model.TopicModelService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TopicModelService(object):
    """Service definition
    """

    @staticmethod
    def TopicAnalysisRequestHandler(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/topic_model.TopicModelService/TopicAnalysisRequestHandler',
            topic__model__pb2.TopicRequest.SerializeToString,
            topic__model__pb2.TopicReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
