apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-reader
#  namespace: default # uncomment to grant within namespace rather than entire cluster
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list"]
