apiVersion: apps/v1
kind: Deployment
metadata:
  name: internal-api-template-service-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: internal-api-template-service
  template:
    metadata:
      labels:
        app: internal-api-template-service
    spec:
      containers:
      - name: internal-api-template-service-container
        image: 379283424934.dkr.ecr.us-east-2.amazonaws.com/mediaviz-repository:internal_api_template_service
        env:
          - name: GRPC_SERVER_PORT
            value: 0.0.0.0:50051
          - name: IMAIGE_PYTHON_APP_ENVIRONMENT
            value: DEV

---

apiVersion: v1
kind: Service
metadata:
  name: internal-api-template-service-service
spec:
  selector:
    app: internal-api-template-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 50051
