apiVersion: apps/v1
kind: Deployment
metadata:
  name: internal-api-template-service-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: internal-api-template-service
  template:
    metadata:
      labels:
        app: internal-api-template-service
    spec:
      containers:
      - name: internal-api-template-service-container
        image: 379283424934.dkr.ecr.us-east-2.amazonaws.com/mediaviz-repository:internal_api_template_service
        env:
          - name: GRPC_SERVER_PORT
            value: 0.0.0.0:50051
          - name: IMAIGE_PYTHON_APP_ENVIRONMENT
            value: DEV
        volumeMounts:
          - name: server-key
            mountPath: /tls_certs/server-key.pem
            subPath: server-key.pem
          - name: server-cert
            mountPath: /tls_certs/server-cert.pem
            subPath: server-cert.pem
          - name: ca-cert
            mountPath: /tls_certs/ca-cert.pem
            subPath: ca-cert.pem
          - name: client-key
            mountPath: /tls_certs/client-key.pem
            subPath: client-key.pem
          - name: client-cert
            mountPath: /tls_certs/client-cert.pem
            subPath: client-cert.pem
      volumes:
      - name: server-key
        secret:
          secretName: tls-certs
          items:
            - key: server-key.pem
              path: server-key.pem
      - name: server-cert
        secret:
          secretName: tls-certs
          items:
            - key: server-cert.pem
              path: server-cert.pem
      - name: ca-cert
        secret:
          secretName: tls-certs
          items:
            - key: ca-cert.pem
              path: ca-cert.pem
      - name: client-key
        secret:
          secretName: tls-certs
          items:
            - key: client-key.pem
              path: client-key.pem
      - name: client-cert
        secret:
          secretName: tls-certs
          items:
            - key: client-cert.pem
              path: client-cert.pem


---

apiVersion: v1
kind: Service
metadata:
  name: internal-api-template-service-service
spec:
  selector:
    app: internal-api-template-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 50051
  type: LoadBalancer
