name: AWS ECR Push

on:
  push:
    branches: 
      - "dev"
      - "qa"
    paths:
      - '**/*'
      - '!.github/workflows/*'
      - '!README.md'
  pull_request:
    branches:
      - "dev"
      - "qa"
      - "main"
    paths:
      - '**/*'
      - '!.github/workflows/*'
      - '!README.md'

env:
  AWS_REGION: "us-east-2"
  ECR_REPOSITORY: ${{ vars.MEDIAVIZ_REPOSITORY_AWS_ECR_URI }}

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: development

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      
    - name: Extract branch name
      id: extract_branch
      run: echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" | sed 's/\//-/g' >> $GITHUB_ENV

    - name: Build the Docker image & deploy to ECS
      id: build-and-deploy-image # may want to separate in future; however, GHA is occasionally finicky with sharing files across steps
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_PUSH_TAG: ${{ github.event.repository.name }}_${{ env.BRANCH_NAME }} # Append the branch name to the image tag
      run: |
        # Build a docker container and
        # push it to ECR so that it can
        # be deployed to ECS.
        echo "image name is $ECR_REPOSITORY:$IMAGE_PUSH_TAG"
        docker build -t $ECR_REPOSITORY:$IMAGE_PUSH_TAG .
        docker push $ECR_REPOSITORY:$IMAGE_PUSH_TAG
        
        echo "image=$ECR_REPOSITORY:$IMAGE_PUSH_TAG:latest" >> $GITHUB_OUTPUT
        echo "image name is $ECR_REPOSITORY:$IMAGE_PUSH_TAG"
        docker build -t $ECR_REPOSITORY:$IMAGE_PUSH_TAG .
        docker push $ECR_REPOSITORY:$IMAGE_PUSH_TAG
        
        echo "image=$ECR_REPOSITORY:$IMAGE_PUSH_TAG:latest" >> $GITHUB_OUTPUT
